language: minimal

services:
  - docker

before_install:
  - docker build --no-cache -t unidata/ldm-docker:latest .
  - mkdir data logs queues
  - docker run --name ldm -e LDM_USER_ID=`id -u` -e LDM_GROUP_ID=`getent group $USER | cut -d':' -f3` -v `pwd`/etc:/home/ldm/etc -v `pwd`/data:/home/ldm/var/data -v `pwd`/queues:/home/ldm/var/queues -v `pwd`/logs:/home/ldm/var/logs -d -p 388:388 unidata/ldm-docker:latest
  
script:
  - docker exec ldm ldmadmin config
